name: 'dtc_fashion_analytics'
version: '1.0.0'
config-version: 2

profile: 'dtc_fashion_analytics'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dtc_fashion_analytics:
    +materialized: view