version: 2

sources:
  - name: raw
    description: Raw Olist data loaded from CSV files
    schema: raw

    tables:
      - name: orders
        description: Raw order-level data
        columns:
          - name: order_id
            description: Unique identifier for each order
            data_tests:
              - not_null
              - unique

      - name: customers
        description: Raw customer data
        columns:
          - name: customer_id
            description: Unique customer identifier
            data_tests:
              - not_null
              - unique

      - name: products
        description: Raw product data
        columns:
          - name: product_id
            description: Unique product identifier
            data_tests:
              - not_null
              - unique

      - name: geolocation
        description: Raw geolocation data
        columns:
          - name: geolocation_zip_code_prefix
            description: Unique geolocation identifier
            data_tests:
              - not_null
              - unique

      - name: order_items
        description: Raw order item data
        columns:
          - name: order_id
            data_tests:
              - not_null

          - name: order_item_id
            data_tests:
              - not_null

          - name: product_id
            data_tests:
              - not_null

          - name: seller_id
            data_tests:
              - not_null

      - name: order_payments
        description: Raw order payments data
        columns:
          - name: order_id
            description: Unique order identifier
            data_tests:
              - not_null
              - unique

      - name: order_reviews
        description: Raw order reviews data
        columns:
          - name: review_id
            data_tests:
              - not_null

          - name: order_id
            data_tests:
              - not_null

      - name: sellers
        description: Raw seller data
        columns:
          - name: seller_id
            description: Unique seller identifier
            data_tests:
              - not_null
              - unique

      - name: category_name_translation
        description: Raw category name translation data
        columns:
          - name: product_category_name
            description: Unique product category identifier
            data_tests:
              - not_null
              - unique
